#pragma once
#include "./include/ECS.h"
#include <string>
#include "./include/GL/glew.h"
#include "./include/GL/gl.h"
#include "./include/GL/glu.h"
#include "./include/GL/glut.h"
#include "./include/GL/freeglut.h"
#include "./include/GL/glext.h"
#include "./include/stb_image.h"
#include <ctime>
#include <iostream>
